C2C-32: Cleaned the echographie form
mekomsolutions/openmrs-config-haiti pull request #35
Opened 2020-09-29 08:58 UTC by reagan-meant

Need some fr locale prrof reading

2020-09-29 14:16 UTC, rbuisson requested changes
See comments

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +a7ad184c-b79a-476d-9ba2-ef980375da28,,CIEL:165387,Foetus Number,Numéro du fœtus,Foetus #,Numéro du fœtus,,,Misc,Numeric,,,,,,,,,,,
This should be 'Number of foetuses/Nombre de fœtus' right?

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +7ce5a9fe-d9e0-427e-a080-ce8a9c673822,,CIEL:1440,Ultrasound Fetal heart rate,Rythme cardiaque fœtal,Fetal heart rate,Rythme cardiaque fœtal,,,Misc,Numeric,,,,FALSE,beats/min,120,160,40,250,,
We should use the already existing 'Fetal Heart Rate' concept.

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +d47e2e11-355e-4c62-86a7-8ebe45fb4292,,CIEL:160090,Ultrasound Presentation,Présentation,Presentation,Présentation,,,Misc,Coded,,Cephalic;Breech;Transverse;Variable,,,,,,,,,
Same here, let's use the already existing 'Presentation.Présentation'

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +6422a83f-acc6-4953-8239-f18a0b6d90a4,,,Ultrasound Estimated date of delivery,Date prévue d'accouchement,Estimated date of delivery,Date prévue d'accouchement,,,Misc,Date,,,,,,,,,,,
Same here, let's use the already existing 'Estimated date of delivery'

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +9e071d37-ee01-4785-a756-7e4059ffe736,,CIEL:1438,Ultrasound Gestational Age,Âge gestationnel par ultrasons,Gestational Age,L'âge gestationnel,,,ConvSet,N/A,,,Number of Weeks; Number of Days,,,,,,,,
And here too

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +4d1f668f-f9b7-4e95-8436-53f37e8c643e,,,Other observations,Autres observations,Other observations,Autres observations,,,Misc,Text,,,,,,,,,,,
This sounds like a generic concept of 'Other' (free text). Is there such a concept already existing?
This concept seems to be part of the "Obstetric ultrasound" set so we'll always be able to diférenciate it from other 'Other' used in various forms.

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +e8ef8004-2d43-43d9-be1d-f1f7f894f99c,,,Observations,Observations,Observations,Observations,,,Misc,Text,,,,,,,,,,,
Is this different from the 'Other observations' concept above?

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/echographie.csv
> +53b255ca-66f2-702b-1c4f-5f4baba006fe,,,Other ultrasound,Autre échographie,Other ultrasound,Autre échographie,,,ConvSet,N/A,,,Observations,,,,,,,,
Not sure what this one represents

2020-09-29 14:16 UTC, rbuisson commented on configuration/concepts/misc.csv
> +5c75e55f-845c-4df6-a6da-b45475a4a215,,,Weight Percentile,Weight Percentile,Centile de poids,Centile de poids,,,Misc,Numeric,,,,,,,,,,,
In french, that'll be 'Percentile'

2020-09-29 17:33 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +a7ad184c-b79a-476d-9ba2-ef980375da28,,CIEL:165387,Foetus Number,Numéro du fœtus,Foetus #,Numéro du fœtus,,,Misc,Numeric,,,,,,,,,,,
Done

2020-09-29 17:37 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +7ce5a9fe-d9e0-427e-a080-ce8a9c673822,,CIEL:1440,Ultrasound Fetal heart rate,Rythme cardiaque fœtal,Fetal heart rate,Rythme cardiaque fœtal,,,Misc,Numeric,,,,FALSE,beats/min,120,160,40,250,,
Done

2020-09-29 17:38 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +d47e2e11-355e-4c62-86a7-8ebe45fb4292,,CIEL:160090,Ultrasound Presentation,Présentation,Presentation,Présentation,,,Misc,Coded,,Cephalic;Breech;Transverse;Variable,,,,,,,,,
Done

2020-09-29 17:43 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +6422a83f-acc6-4953-8239-f18a0b6d90a4,,,Ultrasound Estimated date of delivery,Date prévue d'accouchement,Estimated date of delivery,Date prévue d'accouchement,,,Misc,Date,,,,,,,,,,,
Done

2020-09-29 17:45 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +4d1f668f-f9b7-4e95-8436-53f37e8c643e,,,Other observations,Autres observations,Other observations,Autres observations,,,Misc,Text,,,,,,,,,,,
Done

2020-09-29 21:15 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +53b255ca-66f2-702b-1c4f-5f4baba006fe,,,Other ultrasound,Autre échographie,Other ultrasound,Autre échographie,,,ConvSet,N/A,,,Observations,,,,,,,,
Removed

2020-09-29 21:15 UTC, reagan-meant commented on configuration/concepts/misc.csv
> +5c75e55f-845c-4df6-a6da-b45475a4a215,,,Weight Percentile,Weight Percentile,Centile de poids,Centile de poids,,,Misc,Numeric,,,,,,,,,,,
Fixed

2020-09-30 15:45 UTC, reagan-meant commented on configuration/concepts/echographie.csv
> +9e071d37-ee01-4785-a756-7e4059ffe736,,CIEL:1438,Gestational Age,Âge gestationnel par ultrasons,Gestational Age,L'âge gestationnel,,,ConvSet,N/A,,,Number of Weeks; Number of Days,,,,,,,,
remove the word ultrasound from the fr locale

2020-10-05 07:46 UTC, merged