Cleaned labs to be compatible with OpenELIS
mekomsolutions/openmrs-config-haiti pull request #56
Opened 2020-12-02 01:48 UTC by reagan-meant

WIP

2020-12-07 15:54 UTC, rbuisson approved these changes

2020-12-07 15:58 UTC, rbuisson requested changes
Just few translation changes

2020-12-07 15:58 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +11f699e3-6983-4b27-99cd-07d4bd323a2f,,CIEL:163748,Present,Instant,Present,Instant,,,Misc,N/A,,,,,,,,,,,
Would be "Présent" in fr.

2020-12-07 15:58 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +40f3ff80-44ff-4fad-b0eb-fa89ff05e1f8,,CIEL:163640,Stool Appearance,Selles aspect,Stool Appearance,Selles aspect,,,LabTest,Coded,,Mucus;Sanguineous;Mucosanguineous,,,,,,,,,
Would be "Aspect des selles" in fr

2020-12-07 15:58 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
>  88094e41-e2c7-443f-8770-f46c78e03e7e,,CIEL:163641,Stool Colour,Selles Couleur,Stool Colour,Selles Couleur,,,LabTest,Coded,,Greenish;Blackish;Yellowish;Reddish;Whitish,,,,,,,,,
Would be "Couleur des selles"

2020-12-09 06:51 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +11f699e3-6983-4b27-99cd-07d4bd323a2f,,CIEL:163748,Present,Instant,Present,Instant,,,Misc,N/A,,,,,,,,,,,
Done

2020-12-09 06:52 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +40f3ff80-44ff-4fad-b0eb-fa89ff05e1f8,,CIEL:163640,Stool Appearance,Selles aspect,Stool Appearance,Selles aspect,,,LabTest,Coded,,Mucus;Sanguineous;Mucosanguineous,,,,,,,,,
Done

2020-12-09 06:53 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
>  88094e41-e2c7-443f-8770-f46c78e03e7e,,CIEL:163641,Stool Colour,Selles Couleur,Stool Colour,Selles Couleur,,,LabTest,Coded,,Greenish;Blackish;Yellowish;Reddish;Whitish,,,,,,,,,
Done

2020-12-14 09:10 UTC, rbuisson requested changes

2020-12-14 09:10 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +909a373e-b077-413d-a43e-dc4461f51f20,,CIEL:159663,Gram positive cocci,Coccies Gram +,Gram + cocci,Coccies Gram +,,,LabTest,Coded,,Present;Absent;Indeterminate,,,,,,,,,
En: "Gram-positive Cocci" / "Gram+ Cocci"
Fr: "Cocci à Gram Positif" / "Cocci Gram+"

2020-12-14 09:10 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +1d832608-72a0-4e18-af6c-5d3bc2c18caf,,,Epithelial Cells,Cellules épithélailes,Epithelial Cells,Cellules épithélailes,,,LabTest,Text,,,,,,,,,,,
"épithéliales"

2020-12-14 09:10 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +485af765-a605-4438-88cc-f730414901ab,,,Gram positive diplococci,Diplocoques Gram +,Gram + diplococci,Diplocoques Gram +,,,LabTest,Coded,,Present;Absent;Indeterminate,,,,,,,,,
"Gram-positive Diplococci" etc...

2020-12-14 09:10 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +784a3266-485d-49a3-851f-44hy93df4edb,,,Vaginal Swab (Gram Stain),Frottis vaginal (Gram Stain),Vaginal Swab (Gram Stain),Frottis vaginal (Gram Stain),,,LabSet,N/A,,,Gram positive cocci;Gram negative c
In fr: "Frottis Vaginal (Coloration de Gram)"

2020-12-14 09:10 UTC, rbuisson commented on configuration/concepts/lab_tests.csv
> +784a3266-485d-49a3-851f-2a2c93df4edb,,,Vaginal Swab (Wet Mount),Frottis vaginal (Wet Mount),Vaginal Swab (Wet Mount),Frottis vaginal (Wet Mount),,,LabSet,N/A,,,White Blood Cells;Red Blood Cells;Bacte
Fr: "Frottis vaginal (Goutte pendante)"

2020-12-14 10:58 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +909a373e-b077-413d-a43e-dc4461f51f20,,CIEL:159663,Gram positive cocci,Coccies Gram +,Gram + cocci,Coccies Gram +,,,LabTest,Coded,,Present;Absent;Indeterminate,,,,,,,,,
Done

2020-12-14 11:01 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +1d832608-72a0-4e18-af6c-5d3bc2c18caf,,,Epithelial Cells,Cellules épithélailes,Epithelial Cells,Cellules épithélailes,,,LabTest,Text,,,,,,,,,,,
Done

2020-12-14 11:01 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +485af765-a605-4438-88cc-f730414901ab,,,Gram positive diplococci,Diplocoques Gram +,Gram + diplococci,Diplocoques Gram +,,,LabTest,Coded,,Present;Absent;Indeterminate,,,,,,,,,
Done

2020-12-14 11:02 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +784a3266-485d-49a3-851f-44hy93df4edb,,,Vaginal Swab (Gram Stain),Frottis vaginal (Gram Stain),Vaginal Swab (Gram Stain),Frottis vaginal (Gram Stain),,,LabSet,N/A,,,Gram positive cocci;Gram negative c
Done

2020-12-14 11:03 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +784a3266-485d-49a3-851f-2a2c93df4edb,,,Vaginal Swab (Wet Mount),Frottis vaginal (Wet Mount),Vaginal Swab (Wet Mount),Frottis vaginal (Wet Mount),,,LabSet,N/A,,,White Blood Cells;Red Blood Cells;Bacte
Done

2020-12-15 14:00 UTC, rbuisson commented
Thanks @reagan-meant . Merging.

2020-12-15 14:02 UTC, merged